version: '3.8'

services:
  backend:
    build: .
    container_name: backend
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    depends_on:
      - db
      - redis

  db:
    image: postgres:latest
    container_name: db
    env_file:
      - ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - backend

  celery:
    build: .
    container_name: celery
    command: ["celery", "-A", "kualitex", "worker", "--loglevel=info"]
    volumes:
      - ./backend:/app
    depends_on:
      - backend
      - redis

volumes:
  pg_data:

networks:
  backend:
    driver: bridge
